os: linux
language: python
python: 3.7
services:
    - docker
stages:
- test
- build
- deploy
git:
  submodules: false
cache:
  directories:
  - public
  - $HOME/.docker
  - $HOME/.cache/pip
notifications:
  slack: andi-startup:4EvkZ1UZEV4LwZXzvXhDGP8u
addons:
  ssh_known_hosts: 
  - andi.beta.gouv.fr
  - 40.89.150.201
jobs:
  include:
  ########### TEST
  - stage: test
    name: Test form_handler component
    script:
    - echo "Testing form_handler component"
    - cd form_handler/app
    - pipenv install --dev
    - make tests

  ########### BUILD
  - stage: build
    name: Build docker evolutility
    script:
    - echo "Building commit $TRAVIS_COMMIT"
    - cd evolutility
    - 'docker build -t andi_evolutility
      --build-arg PG_USER=$PG_USER
      --build-arg PG_PASS=$PG_PASS
      --build-arg PG_PORT=$PG_PORT
      --build-arg PG_DB=$PG_DB
      ./

      '
    - docker images
    - docker tag andi_evolutility $DOCKER_USER/private:andi_evolutility
    - docker push $DOCKER_USER/private:andi_evolutility

  - name: Build docker form_handler
    script:
    - cd form_handler
    - 'docker build -t andi_formhandler
      --build-arg ARG_MG_BOX=$MAILGUN_BOX
      --build-arg ARG_MG_KEY=$MAILGUN_KEY
      --build-arg PG_USER=$PG_USER
      --build-arg PG_PASS=$PG_PASS
      --build-arg PG_PORT=$PG_PORT
      --build-arg PG_DB=$PG_DB
      ./

      '
    - docker images
    - docker tag andi_formhandler $DOCKER_USER/private:andi_formhandler
    - docker push $DOCKER_USER/private:andi_formhandler

  - name: Build docker send_bot
    script:
    - cd sendbot
    - 'docker build -t andi_sendbot 
      --build-arg PG_DSN=$PG_DSN
      --build-arg MG_BOX=$MAILGUN_BOX
      --build-arg MG_KEY=$MAILGUN_KEY
      --build-arg AIRTABLE_KEY=$AIRTABLE_KEY
      --build-arg AIRTABLE_BASE_KEY=$AIRTABLE_BASE_KEY_1
      --build-arg SLACK_HOOK=$SLACK_HOOK
      ./

      '
    - docker images
    - docker tag andi_sendbot $DOCKER_USER/private:andi_sendbot
    - docker push $DOCKER_USER/private:andi_sendbot

  - name: Build docker public_graphql
    script:
    - cd public_graphql
    - 'docker build -t andi_publicgraphql
      --build-arg PG_USER=$PG_RO_USER
      --build-arg PG_PASS=$PG_RO_PASS
      --build-arg PG_PORT=$PG_PORT
      --build-arg PG_DB=$PG_DB
      ./

      '
    - docker images
    - docker tag andi_publicgraphql $DOCKER_USER/private:andi_publicgraphql
    - docker push $DOCKER_USER/private:andi_publicgraphql

  ########### DEPLOY
  - stage: deploy
    if: branch = master AND type = push AND fork = false
    name: Deploy docker evolutility
    script:
    - ssh -i deploy_ed25519 travis@$HOST "docker pull berzemus/private:andi_evolutility && sleep 5"
    - ssh -i deploy_ed25519 travis@$HOST "docker stop evolutility && sleep 4 || :"
    - ssh -i deploy_ed25519 travis@$HOST "docker run -d --rm -p 8075:3000
      --add-host=database:172.17.0.1 --name evolutility berzemus/private:andi_evolutility"

  - name: Deploy docker form_handler
    if: branch = master AND type = push AND fork = false
    script:
    - ssh -i deploy_ed25519 travis@$HOST "docker pull berzemus/private:andi_formhandler && sleep 5"
    - ssh -i deploy_ed25519 travis@$HOST "docker stop formhandler && sleep 4 || :"
    - ssh -i deploy_ed25519 travis@$HOST "docker run -d --rm -p 8070:8080
      --add-host=database:172.17.0.1 -v /data/logs:/log --name formhandler
      berzemus/private:andi_formhandler"

  - name: Deploy docker public_graphql
    if: branch = master AND type = push AND fork = false
    script:
    - ssh -i deploy_ed25519 travis@$HOST "docker pull berzemus/private:andi_publicgraphql && sleep 5"
    - ssh -i deploy_ed25519 travis@$HOST "docker stop graphql && sleep 4 || :"
    - ssh -i deploy_ed25519 travis@$HOST "docker run -d --rm -p 8090:8080
      --add-host=database:172.17.0.1 -v /data/logs:/log --name graphql
      berzemus/private:andi_publicgraphql"

  - name: Deploy docker send_bot
    if: branch = master AND type = push AND fork = false
    script:
    - ssh -i deploy_ed25519 travis@$HOST "docker pull berzemus/private:andi_sendbot"
   
before_install:
- openssl aes-256-cbc -K $encrypted_2925775a3854_key -iv $encrypted_2925775a3854_iv
  -in misc/deploy_ed25519.enc -out ./deploy_ed25519 -d
- chmod 600 deploy_ed25519
- echo "$DOCKER_PW" | docker login -u "$DOCKER_USER" --password-stdin
- ssh -i deploy_ed25519 travis@$HOST "echo \"$DOCKER_PW\" | docker login -u \"$DOCKER_USER\" --password-stdin"
- pip install pipenv
