matrix:
    include:
        - name: "Ubuntu 16.0.4 Xenial"
          os: linux
          dist: xenial
          sudo: true
          python:
            - "3.7"
services: "-docker"
language: python
python:
- "3.7"
stages:
- test
- build
- deploy
git:
  submodules: false
dist: trusty
sudo: false
cache:
  directories:
  - public
notifications:
  slack: andi-startup:4EvkZ1UZEV4LwZXzvXhDGP8u
jobs:
  include:
  ########### TEST
  - stage: test
    name: Test form_handler component
    script:
    - echo "Testing form_handler component"
    - cd form_handler/app
    - pipenv install --dev
    - make tests

  ########### BUILD
  - stage: build
    name: Build docker evolutility
    script:
    - echo "Building commit $TRAVIS_COMMIT"
    - cd evolutility
    - 'docker build -t andi_evolutility
      --build-arg PG_USER=$PG_USER
      --build-arg PG_PASS=$PG_PASS
      --build-arg PG_PORT=$PG_PORT
      ./

      '
    - docker images
    - docker tag andi_evolutility $DOCKER_USER/private:andi_evolutility
    - docker push $DOCKER_USER/private:andi_evolutility

  - name: Build docker form_handler
    script:
    - cd form_handler
    - 'docker build -t andi_formhandler
      --build-arg ARG_MG_BOX=$MAILGUN_BOX
      --build-arg ARG_MG_KEY=$MAILGUN_KEY
      --build-arg PG_USER=$PG_USER
      --build-arg PG_PASS=$PG_PASS
      --build-arg PG_PORT=$PG_PORT
      ./

      '
    - docker images
    - docker tag andi_formhandler $DOCKER_USER/private:andi_formhandler
    - docker push $DOCKER_USER/private:andi_formhandler
  - name: Build docker send_bot
    script:
    - cd sendbot
    - 'docker build -t andi_sendbot 
      --build-arg PG_DSN=$PG_DSN
      --build-arg MG_BOX=$MAILGUN_BOX
      --build-arg MG_KEY=$MAILGUN_KEY
      --build-arg AIRTABLE_KEY=$AIRTABLE_KEY
      --build-arg AIRTABLE_BASE_KEY=$AIRTABLE_BASE_KEY_1
      --build-arg SLACK_HOOK=$SLACK_HOOK
      ./

      '
    - docker images
    - docker tag andi_sendbot $DOCKER_USER/private:andi_sendbot
    - docker push $DOCKER_USER/private:andi_sendbot

  ########### DEPLOY
  - stage: deploy
    name: Deploy docker evolutility
    if: branch = master AND type = push AND fork = false
    script:
    - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker pull berzemus/private:andi_evolutility
      || true"
    - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker stop evolutility || true"
    - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker run -d --rm -p 8080:3000
      --add-host=database:172.17.0.1 --ip 172.17.0.2 --name evolutility berzemus/private:andi_evolutility"

  - name: Deploy docker form_handler
    if: branch = master AND type = push AND fork = false
    script:
    - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker pull berzemus/private:andi_formhandler
      || true"
    - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker stop formhandler || true"
    - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker run -d --rm -p 8070:8080
      --add-host=database:172.17.0.1 -v /data/logs:/log --ip 172.17.0.4 --name formhandler
      berzemus/private:andi_formhandler"

  - name: Deploy docker send_bot
    if: branch = master AND type = push AND fork = false
    script:
    - ssh -i deploy_ed25519 travis@andi.beta.gouv.fr "docker pull berzemus/private:andi_sendbot
      || true"
   
addons:
  ssh_known_hosts: andi.beta.gouv.fr
before_install:
- openssl aes-256-cbc -K $encrypted_2925775a3854_key -iv $encrypted_2925775a3854_iv
  -in misc/deploy_ed25519.enc -out ./deploy_ed25519 -d
- chmod 600 deploy_ed25519
- echo "$DOCKER_PW" | docker login -u "$DOCKER_USER" --password-stdin
- pip install pipenv
